### ISSUE TITLE
普通会员角色权限设置不生效

### ISSUE THREAD

**Issue by Ellent70** [cjbi/admin3#12]
![image](https://user-images.githubusercontent.com/56783998/94355728-21be4700-00b9-11eb-86cb-b53d2b1e2ae7.png)
设置为普通会员，但是用普通会员登录进去会跳到404页面。
并且修改普通会员角色权限也不生效

**Comment by erenlu** [comment]
> ![image](https://user-images.githubusercontent.com/56783998/94355728-21be4700-00b9-11eb-86cb-b53d2b1e2ae7.png)
> 设置为普通会员，但是用普通会员登录进去会跳到404页面。
> 并且修改普通会员角色权限也不生效

你好！请问你成功导入项目的时候，只操作了 `read me`  里面的步骤吗？ 我成功运行后端程序后无法在本地打开localhost:8080的网页。谢谢！

**Comment by Ellent70** [comment]
不是，还修改了后台代码，我这里出现了跨域问题。还有配置文件需要配置为开发环境

**Comment by cjbi** [comment]
已经修复
