### ISSUE TITLE
开发者你好，请问为什么我打开这个项目就这样部分乱码，数据库我也改成了utf8可是还是这样

### ISSUE THREAD

**Issue by ZOEPAN333** [cjbi/admin3#15]
![QQ截图20201202175649](https://user-images.githubusercontent.com/68172319/100861352-acae2a00-34cc-11eb-982c-77c469deaee8.png)

**Comment by ZOEPAN333** [comment]
图片不显示，就是左侧菜单栏乱码，其他部分正常

**Comment by ZOEPAN333** [comment]
![乱码7](https://user-images.githubusercontent.com/68172319/100862450-21ce2f00-34ce-11eb-9910-b1ddd29d4d14.jpg)

**Comment by ZOEPAN333** [comment]
用户管理-权限列表页显示就是正常的

**Comment by whe0512** [comment]
配置文件的数据库连接，添加useUnicode=true&characterEncoding=UTF-8

**Comment by cjbi** [comment]
已经修复
