### ISSUE TITLE
前端框架更新？ 比如vite 4.0

### ISSUE THREAD

**Issue by PlexPt** [cjbi/admin3#55]
┌────────────────────────────┬─────────┬────────┐
│ Package                    │ Current │ Latest │
├────────────────────────────┼─────────┼────────┤
│ @vitejs/plugin-vue (dev)   │ 3.2.0   │ 4.0.0  │
├────────────────────────────┼─────────┼────────┤
│ vite (dev)                 │ 3.2.5   │ 4.0.4  │
├────────────────────────────┼─────────┼────────┤
│ axios                      │ 0.27.2  │ 1.2.4  │
├────────────────────────────┼─────────┼────────┤
│ unplugin-auto-import (dev) │ 0.11.5  │ 0.12.2 │
├────────────────────────────┼─────────┼────────┤
│ vue-tsc (dev)              │ 0.38.9  │ 1.0.24 │
└────────────────────────────┴─────────┴────────┘

一些依赖已经落后很多版本了

**Comment by cjbi** [comment]
最近会安排上的，也欢迎贡献代码
