### ISSUE TITLE
关于SessionService的提问

### ISSUE THREAD

**Issue by Virtuoso461** [cjbi/admin3#83]
为什么SessionService用的是接口而不是类

**Comment by rkodang** [comment]
我已经收到您的来信啦 Thanks~

**Comment by cjbi** [comment]
使用接口是因为希望能够分离技术细节，放在infra包中去实现会话功能。另一方面提供的会话实现只满足单机情形，使用者不满意的话可以自己去扩展实现，例如实现redis版本来满足集群情况下的缓存共享
