### ISSUE TITLE
使用H2数据库时出现无法插入数据

### ISSUE THREAD

**Issue by sdlhappylin** [cjbi/admin3#85]
当使用H2作为数据库时无法从data.sql插入数据
我排查了原因如下：
> tech.wetech.admin3.sys.model.User类生成的表user与H2系统USER表重复了，导致无法插入数据
> 建议修改一下User类的名或者@Entity注解中修改命名，避开各大数据库内部表名，或者添加全局表前缀

**Comment by rkodang** [comment]
我已经收到您的来信啦 Thanks~

**Comment by cjbi** [comment]
> data

感谢反馈问题

**Comment by cjbi** [comment]
使用引号创建表，能解决关键字的问题，例如：INSERT INTO "user" (...) values (...)
